### ISSUE TITLE
Is the widget works for EWM 7.0.1 verison

### ISSUE THREAD

**Issue by tejapolaki** [jazz-community/rtc-absence-widget#3]
Hi Team,

We have recently upgrade RTC to version 7.0.1 and want to check is this plugin is supported din this latest version.

Thanks,
Teja

**Comment by schneigu** [comment]
Hello Teja,
We are using it since several month on EWM 7.0.1 without any issue.

Regards
Guido

**Comment by tejapolaki** [comment]
Thank you, will install.
